# Generated by Django 4.2.27 on 2026-01-26 02:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CollectionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial Success"),
                            ("failed", "Failed"),
                        ],
                        default="success",
                        max_length=10,
                    ),
                ),
                ("cryptos_processed", models.PositiveIntegerField(default=0)),
                ("cryptos_failed", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                (
                    "execution_time_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Execution time in milliseconds",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection Log",
                "verbose_name_plural": "Collection Logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Cryptocurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        db_index=True,
                        help_text="Trading symbol (e.g., BTC, ETH)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name (e.g., Bitcoin, Ethereum)", max_length=100
                    ),
                ),
                (
                    "coingecko_id",
                    models.CharField(
                        help_text="CoinGecko API identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="URL for cryptocurrency logo",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether to track this cryptocurrency",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cryptocurrency",
                "verbose_name_plural": "Cryptocurrencies",
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="PriceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_price",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Target price to trigger alert",
                        max_digits=24,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("above", "Price goes above"),
                            ("below", "Price goes below"),
                        ],
                        default="above",
                        help_text="Condition to trigger the alert",
                        max_length=10,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="Optional note for this alert"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this alert is active",
                    ),
                ),
                (
                    "is_triggered",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this alert has been triggered",
                    ),
                ),
                (
                    "triggered_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Price when alert was triggered",
                        max_digits=24,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "triggered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when alert was triggered",
                        null=True,
                    ),
                ),
                (
                    "cryptocurrency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="core.cryptocurrency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Alert",
                "verbose_name_plural": "Price Alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_usd",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Price in USD",
                        max_digits=24,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "price_brl",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price in BRL",
                        max_digits=24,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "market_cap_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Market capitalization in USD",
                        max_digits=30,
                        null=True,
                    ),
                ),
                (
                    "volume_24h_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="24-hour trading volume in USD",
                        max_digits=30,
                        null=True,
                    ),
                ),
                (
                    "change_1h",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Price change percentage in last 1 hour",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "change_24h",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Price change percentage in last 24 hours",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "change_7d",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Price change percentage in last 7 days",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the price was collected",
                    ),
                ),
                (
                    "cryptocurrency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="core.cryptocurrency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price History",
                "verbose_name_plural": "Price Histories",
                "ordering": ["-collected_at"],
                "indexes": [
                    models.Index(
                        fields=["cryptocurrency", "-collected_at"],
                        name="core_priceh_cryptoc_646cd6_idx",
                    ),
                    models.Index(
                        fields=["-collected_at"], name="core_priceh_collect_c15c90_idx"
                    ),
                ],
            },
        ),
    ]
