# Generated by Django 4.2.27 on 2026-03-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricealert",
            name="owner_token_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Hashed anonymous client token used to manage this alert",
                max_length=64,
            ),
        ),
    ]
