# Generated by Django 4.2.27 on 2026-03-17 19:00

from decimal import Decimal

from django.db import migrations, models


def mark_legacy_brl_estimates(apps, schema_editor):
    PriceHistory = apps.get_model("core", "PriceHistory")
    estimated_multiplier = Decimal("5")
    suspect_rows = []

    queryset = PriceHistory.objects.filter(
        models.Q(change_1h__isnull=False) | models.Q(change_7d__isnull=False)
    )

    for price_history in queryset.iterator():
        estimated_brl = (price_history.price_usd * estimated_multiplier).quantize(
            Decimal("0.01")
        )
        if price_history.price_brl == estimated_brl:
            price_history.is_brl_estimated = True
            suspect_rows.append(price_history)

        if len(suspect_rows) >= 500:
            PriceHistory.objects.bulk_update(suspect_rows, ["is_brl_estimated"])
            suspect_rows.clear()

    if suspect_rows:
        PriceHistory.objects.bulk_update(suspect_rows, ["is_brl_estimated"])


def unmark_legacy_brl_estimates(apps, schema_editor):
    PriceHistory = apps.get_model("core", "PriceHistory")
    PriceHistory.objects.filter(is_brl_estimated=True).update(is_brl_estimated=False)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_pricealert_owner_token_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricehistory",
            name="is_brl_estimated",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether the stored BRL price is only an estimate",
            ),
        ),
        migrations.RunPython(
            mark_legacy_brl_estimates,
            unmark_legacy_brl_estimates,
        ),
    ]
