# Generated by Django 4.2.29 on 2026-03-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pricehistory_is_brl_estimated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionlog',
            name='cryptos_failed',
        ),
        migrations.AlterField(
            model_name='collectionlog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=10),
        ),
    ]
